version: '3'

services:
  php:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./html/:/var/www/html/
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    restart: always
    ports:
      - 8000:80
    depends_on:
      mysql:
        condition: service_healthy

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./nginx/nginx.conf:etc/nginx/nginx.conf:ro
  #   command: [ nginx, '-g', 'daemon off;' ]
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     - NGINX_HOST=localhost
  #     - NGINX_PORT=80
  #   depends_on:
  #     - php

  mysql:
    image: mysql
    restart: always
    environment:
      # MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_PASSWORD: mypass
      # MYSQL_DATABASE: appDB2
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "9906:3306"
    volumes:
      # - ./mysql-init/:/docker-entrypoint-initdb.d/:ro
      - ./html/database/:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 1s
      retries: 5

volumes:
  mysql:
